[package]
name = "majorlauncher"
description = "Окно MajorLauncher: Tauri + Svelte, только отображение и кнопки"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
majorlauncher-core = { path = "../../core" }
